---
- name: install ddclient
  action: apt pkg=ddclient state=latest
- name: configure ddclient
  action: >
    template src={{ item }}.j2
    dest=/etc/{{ item }}
    backup=no
    owner=root
    group=root
    mode=0600
  notify:
    - restart ddclient
  with_items:
    - ddclient.conf
